language: php
php:
  - 7.4
sudo: false
before_script:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer install
script:
  - vendor/bin/phpcs --standard=PSR2 src/
  - vendor/bin/phpunit -c phpunit.xml
after_script:
  - ./bin/codeclimate.sh